### ISSUE TITLE
kirki-fallback.php

### ISSUE THREAD

**Issue by carasmo** [aristath/_s#12]
In the background fallback, the $key is undefined and when Kirki is deactivated there is a variable missing error and all the other CSS is messed up. I am at a loss on how to fix this, sorry.

**Comment by aristath** [comment]
Can you try deleting these lines? https://github.com/aristath/_s/blob/master/inc/kirki-fallback.php#L162-L195
It should work without them now that we have a proper background field

**Comment by carasmo** [comment]
Hello! I deleted those lines (see image) and no output for background at all. The other CSS is fine. Am I making the field correctly?

```
	Theme_Prefix_Kirki::add_field( 'theme_prefix', array( 
	'type'        => 'background',
	'settings'    => 'body_background',
	'label'       => __( 'Body Background', 'txtdomain' ),
	'section'     => 'backgrounds',
	'transport'   => 'auto',
		'default'		 => array(
			'background-image'      => '',
			'background-color'      => '#f3ebe2',
			'background-repeat'     => 'repeat-all',
			'background-size'       => 'auto',
			'background-attachment' => 'fixed',
			'background-position'   => 'left top',
		),
        'output' => array( 
            array( 
                'element'     => 'body',
                'media_query' => '@media ( min-width: 480px )',
             ),
         ),
	) );


```

![screen shot 2017-08-20 at 11 09 30 am](https://user-images.githubusercontent.com/1124594/29496029-227ddc68-8598-11e7-81b6-d2c77251c754.png)

**Comment by aristath** [comment]
@carasmo I'm sorry, I didn't have time to work on this these days, I'm working on rewriting that class now, I'll post an update here as soon as that's finished. 👍

**Comment by aristath** [comment]
Fixed in https://github.com/aristath/_s/commit/f7a7c3e513eb62f41ffdeb9f76d83762230e1b1b 👍
